### ISSUE TITLE
Scratch - JPEG import is currently broken

### ISSUE THREAD

**Issue by THS-on** [Lernstick/lernstickAdvanced#14]
Debian uses an old version of squeak-vm and builds against a new version of libjpeg. 
This is a problem because only the old modified version of libjpeg works correctly. 
There is a fix for that here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744289#46
Or we could try to update to a newer version, but  currently in unstable there is only 4.10 (latest version is 5.1).

**Comment by joberkel** [comment]
Lernstick now uses online version of scratch
