### ISSUE TITLE
Adding python support with anaconda or minconda

### ISSUE THREAD

**Issue by deebuls** [Lernstick/lernstickAdvanced#16]
Hi everyone,

I wanted to add python library support with anaconda to the iso.
What is the steps to start with the current iso and adding new libraries.

**Comment by THS-on** [comment]
You can easily remaster your iso with your utility called dlcopy. You just install your packages and create a new iso.
German Documentation: https://docs.google.com/document/d/1jbCpIGR11GUtUXX4KuEijajBvsRR_1qWZFNh4Y2_l2o/edit#heading=h.hm8gnjlcpczf

**Comment by joberkel** [comment]
We use the default python shipping by pipx
